security:
    encoders:
        AppBundle\Entity\Joueur:
            algorithm: bcrypt
            
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Joueur
                property: username

    firewalls:
        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
